name: CI
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: develop

  pull_request:
    branches: develop

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: '14.6'
      - run: npm install 

      - name: Compile production assets
        run: npm run prod
      
      - name: Remove node_modules
        run: rm -Rf node_modules

      - name: Remove .git
        run: rm -Rf .git

      - name: GitHub Action for WP Engine Git Deployment
        uses: wpengine/github-action-wpe-site-deploy@main
        env:

          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPENGINE_SSH_KEY_PRIVATE }}
          PHP_LINT: FALSE
          FLAGS: -azvr --inplace --exclude=".*"
          TPO_SRC_PATH: ""
          TPO_PATH: "wp-content/themes/tti-starter-tw/"

          # Branches & Environments 
          PRD_ENV: ${{ secrets.WPENGINE_ENVIRONMENT_NAME }}
          PRD_BRANCH: develop


